site_name: 'Llama Stack Agentic AI Workflow - Template Documentation'
nav:
  - Overview: index.md
  - Prerequisites: template-prerequisites.md
  - Template Usage: usage.md
  - Remote Cluster Configuration: template-remote-cluster.md
  - Deployed Application: application.md
plugins:
  - techdocs-core

